INSERT INTO
	books(book_name, publish_year, image_path, book_description, author)
VALUES
	("Clean Code", "2005", "clean-code.jpg", "Book about code style wirtted by Uncle Bob", "Uncle Bob"),
	("AAA", "0000", "aaa.jpg", "Book about aaa", "Uncle Bob"),
	("BBB", "1", "bbb.jpg", "Book about bbb", "Bbbbb Bbbbb"),
	("CCC", "2", "ccc.jpg", "Book about ccc", "Ccccc Ccccc"),
	("DDD", "3", "ddd.jpg", "Book about ddd", "Ddddd Ddddd"),
	("EEE", "4", "eee.jpg", "Book about eee", "Eeeee Eeeee"),
	("FFF", "5", "fff.jpg", "Book about fff", "Fffff fffff"),
	("GGG", "6", "ggg.jpg", "Book about ggg", "Ggggg Ggggg"),
	("HHH", "7", "hhh.jpg", "Book about hhh", "Hhhhh hhhhh"),
	("III", "8", "iii.jpg", "Book about iii", "Iiiii Iiiii"),
	("JJJ", "9", "jjj.jpg", "Book about jjj", "Jjjjj JJjjj"),
	("KKK", "10", "kkk.jpg", "Book about kkk", "Kkkkk Kkkkk"),
	("LLL", "11", "lll.jpg", "Book about lll", "Lllll Lllll"),
	("MMM", "12", "mmm.jpg", "Book about mmm", "Mmmmm Mmmmm"),
	("NNN", "13", "nnn.jpg", "Book about nnn", "Nnnnn Nnnnn"),
	("OOO", "14", "ooo.jpg", "Book about ooo", "Ooooo Ooooo"),
	("PPP", "15", "ppp.jpg", "Book about ppp", "Ppppp Ppppp"),
	("QQQ", "16", "qqq.jpg", "Book about qqq", "Qqqqq Qqqqq"),
	("RRR", "17", "rrr.jpg", "Book about rrr", "Rrrrr Rrrrr"),
	("SSS", "18", "sss.jpg", "Book about sss", "Sssss Sssss"),
	("TTT", "19", "ttt.jpg", "Book about ttt", "Ttttt Ttttt"),
	("UUU", "20", "uuu.jpg", "Book about uuu", "Uuuuu UUuuu"),
	("VVV", "21", "vvv.jpg", "Book about vvv", "Vvvvv Vvvvv"),
	("WWW", "22", "www.jpg", "Book about www", "Wwwww Wwwww"),
	("XXX", "23", "xxx.jpg", "Book about xxx", "Xxxxx Xxxxx"),
	("YYY", "24", "yyy.jpg", "Book about yyy", "Yyyyy Yyyyy"),
	("ZZZ", "25", "zzz.jpg", "Book about zzz", "Zzzzz Zzzzz"),
	("111", "26", "111.jpg", "Book about 111", "11111 11111"),
	("222", "27", "222.jpg", "Book about 222", "22222 22222"),
	("333", "28", "333.jpg", "Book about 333", "33333 33333"),
	("444", "29", "444.jpg", "Book about 444", "44444 44444");